import type { ContentModule, FlashCard } from "@/lib/types";

const vocab: FlashCard[] = [
  { front: "時々[ときどき]", reading: "ときどき", meaning: { en: "sometimes", id: "kadang-kadang" } },
  { front: "大抵[たいてい]", reading: "たいてい", meaning: { en: "usually, mostly", id: "biasanya" } },
  { front: "多分[たぶん]", reading: "たぶん", meaning: { en: "probably", id: "mungkin" } },
  { front: "一緒[いっしょ]に", reading: "いっしょに", meaning: { en: "together", id: "bersama" } },
  { front: "初[はじ]めて", reading: "はじめて", meaning: { en: "for the first time", id: "untuk pertama kali" } },
  { front: "急[いそ]ぐ", reading: "いそぐ", meaning: { en: "to hurry", id: "bergegas" } },
  { front: "手伝[てつだ]う", reading: "てつだう", meaning: { en: "to help", id: "membantu" } },
  { front: "選[えら]ぶ", reading: "えらぶ", meaning: { en: "to choose", id: "memilih" } },
  { front: "運[はこ]ぶ", reading: "はこぶ", meaning: { en: "to carry", id: "membawa/mengangkut" } },
  { front: "止[と]まる", reading: "とまる", meaning: { en: "to stop (intransitive)", id: "berhenti" } },
  { front: "始[はじ]める", reading: "はじめる", meaning: { en: "to begin (something)", id: "memulai" } },
  { front: "遅[おく]れる", reading: "おくれる", meaning: { en: "to be late", id: "terlambat" } },
  { front: "忘[わす]れる", reading: "わすれる", meaning: { en: "to forget", id: "lupa" } },
  { front: "調[しら]べる", reading: "しらべる", meaning: { en: "to look up, investigate", id: "memeriksa, menyelidiki" } },
  { front: "答[こた]える", reading: "こたえる", meaning: { en: "to answer", id: "menjawab" } },
  { front: "危[あぶ]ない", reading: "あぶない", meaning: { en: "dangerous", id: "berbahaya" } },
  { front: "寂[さび]しい", reading: "さびしい", meaning: { en: "lonely", id: "kesepian" } },
  { front: "急[きゅう]に", reading: "きゅうに", meaning: { en: "suddenly", id: "tiba-tiba" } },
  { front: "簡単[かんたん]", reading: "かんたん", meaning: { en: "simple, easy", id: "sederhana, mudah" } },
  { front: "大切[たいせつ]", reading: "たいせつ", meaning: { en: "important, precious", id: "penting, berharga" } },
  { front: "熱心[ねっしん]", reading: "ねっしん", meaning: { en: "enthusiastic, diligent", id: "bersemangat, tekun" } },
  { front: "丁寧[ていねい]", reading: "ていねい", meaning: { en: "polite, careful", id: "sopan, teliti" } },
  { front: "受付[うけつけ]", reading: "うけつけ", meaning: { en: "reception desk", id: "meja resepsi" } },
  { front: "約束[やくそく]", reading: "やくそく", meaning: { en: "promise, appointment", id: "janji" } },
  { front: "用事[ようじ]", reading: "ようじ", meaning: { en: "an errand, something to do", id: "urusan/keperluan" } },
  { front: "都合[つごう]", reading: "つごう", meaning: { en: "convenience, circumstances", id: "kondisi/waktu luang" } },
  { front: "説明[せつめい]", reading: "せつめい", meaning: { en: "explanation", id: "penjelasan" } },
  { front: "経験[けいけん]", reading: "けいけん", meaning: { en: "experience", id: "pengalaman" } },
  { front: "文化[ぶんか]", reading: "ぶんか", meaning: { en: "culture", id: "budaya" } },
  { front: "生活[せいかつ]", reading: "せいかつ", meaning: { en: "daily life", id: "kehidupan sehari-hari" } },
  { front: "会議[かいぎ]", reading: "かいぎ", meaning: { en: "meeting, conference", id: "rapat" } },
  { front: "予定[よてい]", reading: "よてい", meaning: { en: "plan, schedule", id: "rencana, jadwal" } },
  { front: "最近[さいきん]", reading: "さいきん", meaning: { en: "recently", id: "belakangan ini" } },
  { front: "将来[しょうらい]", reading: "しょうらい", meaning: { en: "future", id: "masa depan" } },
  { front: "表[おもて]", reading: "おもて", meaning: { en: "front, surface, outside", id: "bagian depan/luar" } },
  { front: "続[つづ]く", reading: "つづく", meaning: { en: "to continue (intransitive)", id: "berlanjut" } },
  { front: "準備[じゅんび]", reading: "じゅんび", meaning: { en: "preparation", id: "persiapan" } },
  { front: "用意[ようい]", reading: "ようい", meaning: { en: "preparation, arrangements", id: "persiapan" } },
  { front: "増[ふ]える", reading: "ふえる", meaning: { en: "to increase (intransitive)", id: "bertambah" } },
  { front: "減[へ]る", reading: "へる", meaning: { en: "to decrease (intransitive)", id: "berkurang" } },
];

const kanji: FlashCard[] = [
  { front: "study — 勉", reading: "ベン", meaning: { en: "exertion, diligence — 勉強[べんきょう] study", id: "usaha, ketekunan — 勉強 belajar" } },
  { front: "強", reading: "キョウ・つよい", meaning: { en: "strong — 強[つよ]い, 勉強[べんきょう]", id: "kuat — 強い, 勉強" } },
  { front: "旅", reading: "リョ・たび", meaning: { en: "trip — 旅行[りょこう] travel", id: "perjalanan — 旅行" } },
  { front: "館", reading: "カン", meaning: { en: "large building — 図書館[としょかん], 映画館[えいがかん]", id: "gedung besar — 図書館, 映画館" } },
  { front: "映", reading: "エイ", meaning: { en: "reflect, projection — 映画[えいが] movie", id: "memantulkan, proyeksi — 映画" } },
  { front: "画", reading: "ガ・カク", meaning: { en: "picture, stroke — 映画[えいが], 計画[けいかく]", id: "gambar, guratan — 映画, 計画" } },
  { front: "駅", reading: "エキ", meaning: { en: "station — 駅[えき]", id: "stasiun — 駅" } },
  { front: "地", reading: "チ・ジ", meaning: { en: "ground, land — 地図[ちず] map, 地下[ちか]", id: "tanah — 地図, 地下" } },
  { front: "鉄", reading: "テツ", meaning: { en: "iron — 地下鉄[ちかてつ] subway", id: "besi — 地下鉄" } },
  { front: "会", reading: "カイ・あう", meaning: { en: "meet — 会[あ]う, 会社[かいしゃ], 会議[かいぎ]", id: "bertemu — 会う, 会社, 会議" } },
  { front: "社", reading: "シャ", meaning: { en: "company, shrine — 会社[かいしゃ], 神社[じんじゃ]", id: "perusahaan, kuil — 会社, 神社" } },
  { front: "特", reading: "トク", meaning: { en: "special — 特[とく]に especially, 特急[とっきゅう]", id: "khusus — 特に, 特急" } },
  { front: "急", reading: "キュウ・いそぐ", meaning: { en: "hurry, sudden — 急[いそ]ぐ, 急[きゅう]に", id: "buru-buru, mendadak — 急ぐ, 急に" } },
  { front: "度", reading: "ド", meaning: { en: "degree, time(s) — 一度[いちど], 今度[こんど]", id: "derajat, kali — 一度, 今度" } },
  { front: "都", reading: "ト・ツ", meaning: { en: "capital, metropolis — 東京都[とうきょうと], 都合[つごう]", id: "ibu kota — 東京都, 都合" } },
  { front: "研", reading: "ケン", meaning: { en: "polish, research — 研究[けんきゅう] research", id: "meneliti — 研究" } },
  { front: "究", reading: "キュウ", meaning: { en: "research thoroughly — 研究[けんきゅう]", id: "menyelidiki tuntas — 研究" } },
  { front: "業", reading: "ギョウ", meaning: { en: "work, industry — 授業[じゅぎょう] class, 工業[こうぎょう]", id: "pekerjaan, industri — 授業, 工業" } },
  { front: "授", reading: "ジュ", meaning: { en: "grant, teach — 授業[じゅぎょう], 教授[きょうじゅ]", id: "memberi, mengajar — 授業, 教授" } },
  { front: "英", reading: "エイ", meaning: { en: "England, brilliant — 英語[えいご] English", id: "Inggris — 英語" } },
  { front: "説", reading: "セツ", meaning: { en: "theory, explain — 説明[せつめい], 小説[しょうせつ]", id: "teori, menjelaskan — 説明, 小説" } },
  { front: "明", reading: "メイ・あかるい", meaning: { en: "bright, clear — 明[あか]るい, 説明[せつめい]", id: "terang, jelas — 明るい, 説明" } },
];

export const n5VocabKanji: ContentModule = {
  type: "deck",
  slug: "n5-vocab-kanji",
  title: { en: "N5 Vocab & Kanji Refresher", id: "Penyegaran Kosakata & Kanji N5" },
  description: {
    en: "High-frequency words and kanji that bridge N5 into N4. Flip through the decks, then take the quiz.",
    id: "Kata dan kanji frekuensi tinggi yang menjembatani N5 ke N4. Bolak-balik kartunya, lalu kerjakan kuisnya.",
  },
  decks: [
    { id: "vocab", label: { en: "Vocabulary", id: "Kosakata" }, cards: vocab },
    { id: "kanji", label: { en: "Kanji", id: "Kanji" }, cards: kanji },
  ],
  quiz: [
    {
      id: "n5-vocab-kanji:quiz",
      title: { en: "Meaning check", id: "Cek arti" },
      questions: [
        {
          kind: "mcq",
          ja: "約束[やくそく]",
          prompt: { en: "means…", id: "berarti…" },
          options: [
            { en: "promise / appointment", id: "janji" },
            { en: "preparation", id: "persiapan" },
            { en: "experience", id: "pengalaman" },
            { en: "explanation", id: "penjelasan" },
          ],
          answer: 0,
        },
        {
          kind: "mcq",
          ja: "最近[さいきん]",
          prompt: { en: "means…", id: "berarti…" },
          options: [
            { en: "in the future", id: "di masa depan" },
            { en: "recently", id: "belakangan ini" },
            { en: "suddenly", id: "tiba-tiba" },
            { en: "usually", id: "biasanya" },
          ],
          answer: 1,
        },
        {
          kind: "mcq",
          prompt: { en: "Which kanji compound means \"subway\"?", id: "Gabungan kanji mana yang berarti \"kereta bawah tanah\"?" },
          options: ["地図", "地下鉄", "電車", "特急"],
          answer: 1,
        },
        {
          kind: "mcq",
          ja: "授業[じゅぎょう]",
          prompt: { en: "means…", id: "berarti…" },
          options: [
            { en: "meeting", id: "rapat" },
            { en: "research", id: "penelitian" },
            { en: "(school) class / lesson", id: "pelajaran / kuliah" },
            { en: "homework", id: "PR" },
          ],
          answer: 2,
        },
        {
          kind: "mcq",
          ja: "増[ふ]える ⇔ ___",
          prompt: { en: "The opposite is:", id: "Lawan katanya:" },
          options: ["減[へ]る", "続[つづ]く", "止[と]まる", "遅[おく]れる"],
          answer: 0,
        },
      ],
    },
  ],
};
